### ISSUE TITLE
Heroku Application Logs

### ISSUE THREAD

**Issue by david-at-ocs** [david-at-ocs/07-16-ActiveRecord-atomics#2]
2015-07-17T16:05:04.240717+00:00 heroku[api]: Enable Logplex by dgardetti@gmail.com
2015-07-17T16:05:04.240717+00:00 heroku[api]: Release v2 created by dgardetti@gmail.com
2015-07-17T16:06:55.658169+00:00 heroku[api]: Attach DATABASE resource by dgardetti@gmail.com
2015-07-17T16:06:55.658169+00:00 heroku[api]: Release v3 created by dgardetti@gmail.com
2015-07-17T16:08:59.593260+00:00 heroku[api]: Set LANG, RACK_ENV config vars by dgardetti@gmail.com
2015-07-17T16:08:59.593260+00:00 heroku[api]: Release v4 created by dgardetti@gmail.com
2015-07-17T16:08:59.986493+00:00 heroku[slug-compiler]: Slug compilation started
2015-07-17T16:08:59.986516+00:00 heroku[slug-compiler]: Slug compilation finished
2015-07-17T16:08:59.887415+00:00 heroku[api]: Scale to web=1 by dgardetti@gmail.com
2015-07-17T16:08:59.931655+00:00 heroku[api]: Deploy a92f21c by dgardetti@gmail.com
2015-07-17T16:08:59.931655+00:00 heroku[api]: Release v5 created by dgardetti@gmail.com
2015-07-17T16:09:02.557429+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 49167`
2015-07-17T16:09:05.026909+00:00 app[web.1]: /app/app.rb:5:in `require': cannot load such file -- sqlite3 (LoadError)
2015-07-17T16:09:05.026946+00:00 app[web.1]:    from /app/app.rb:5:in`<top (required)>'
2015-07-17T16:09:05.026948+00:00 app[web.1]:    from /app/config.ru:1:in `require'
2015-07-17T16:09:05.026950+00:00 app[web.1]:    from /app/config.ru:1:in`block in <main>'
2015-07-17T16:09:05.026952+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
2015-07-17T16:09:05.026953+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in`initialize'
2015-07-17T16:09:05.026955+00:00 app[web.1]:    from /app/config.ru:in `new'
2015-07-17T16:09:05.026956+00:00 app[web.1]:    from /app/config.ru:in`<main>'
2015-07-17T16:09:05.026958+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
2015-07-17T16:09:05.026959+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in`new_from_string'
2015-07-17T16:09:05.026963+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2015-07-17T16:09:05.026961+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in`parse_file'
2015-07-17T16:09:05.026965+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
2015-07-17T16:09:05.026966+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:336:in`wrapped_app'
2015-07-17T16:09:05.026968+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
2015-07-17T16:09:05.026969+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:147:in`start'
2015-07-17T16:09:05.026973+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
2015-07-17T16:09:05.026975+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in`load'
2015-07-17T16:09:05.026977+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `<main>'
2015-07-17T16:09:05.768635+00:00 heroku[web.1]: Process exited with status 1
2015-07-17T16:09:05.784721+00:00 heroku[web.1]: State changed from starting to crashed
2015-07-17T16:09:05.785775+00:00 heroku[web.1]: State changed from crashed to starting
2015-07-17T16:09:08.287202+00:00 heroku[web.1]: Starting process with command`bundle exec rackup config.ru -p 34788`
2015-07-17T16:09:10.897277+00:00 app[web.1]: /app/app.rb:5:in`require': cannot load such file -- sqlite3 (LoadError)
2015-07-17T16:09:10.897303+00:00 app[web.1]:    from /app/app.rb:5:in `<top (required)>'
2015-07-17T16:09:10.897305+00:00 app[web.1]:    from /app/config.ru:1:in`require'
2015-07-17T16:09:10.897308+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
2015-07-17T16:09:10.897306+00:00 app[web.1]:    from /app/config.ru:1:in`block in <main>'
2015-07-17T16:09:10.897310+00:00 app[web.1]:    from /app/config.ru:in `new'
2015-07-17T16:09:10.897309+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in`initialize'
2015-07-17T16:09:10.897312+00:00 app[web.1]:    from /app/config.ru:in `<main>'
2015-07-17T16:09:10.897313+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in`eval'
2015-07-17T16:09:10.897317+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
2015-07-17T16:09:10.897318+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in`parse_file'
2015-07-17T16:09:10.897320+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
2015-07-17T16:09:10.897324+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:208:in`app'
2015-07-17T16:09:10.897327+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
2015-07-17T16:09:10.897331+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:272:in`start'
2015-07-17T16:09:10.897334+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
2015-07-17T16:09:10.897338+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/bin/rackup:4:in`<top (required)>'
2015-07-17T16:09:10.897343+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `<main>'
2015-07-17T16:09:10.897342+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in`load'
2015-07-17T16:09:11.716797+00:00 heroku[web.1]: Process exited with status 1
2015-07-17T16:09:11.726058+00:00 heroku[web.1]: State changed from starting to crashed
2015-07-17T16:11:58.607673+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=murmuring-badlands-7467.herokuapp.com request_id=3f673113-ba1d-4568-b58e-7fa322d4bfbd fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:11:59.116739+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=murmuring-badlands-7467.herokuapp.com request_id=33acee52-aeca-43cd-a486-f7a6f1cb34d5 fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:12:09.917399+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/home" host=murmuring-badlands-7467.herokuapp.com request_id=e8210349-ed62-4de8-bdf7-b3c070349020 fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:12:10.150667+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=murmuring-badlands-7467.herokuapp.com request_id=0072d0c6-488c-44d7-9c04-92ef35a6ebaf fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:12:18.966287+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=murmuring-badlands-7467.herokuapp.com request_id=6ee0e31a-b11c-4953-9afd-4685a0290039 fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:12:19.147395+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=murmuring-badlands-7467.herokuapp.com request_id=aa0f4704-2fe0-4a49-9536-eafdec8d9402 fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:12:39.093265+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=murmuring-badlands-7467.herokuapp.com request_id=40bffbc3-3c0b-487b-a68e-ea0d58960cab fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:12:39.408425+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=murmuring-badlands-7467.herokuapp.com request_id=6d385ff1-a257-4d7d-8fd2-68754efa3ea6 fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:12:41.391182+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=murmuring-badlands-7467.herokuapp.com request_id=b519c7d9-352c-41ed-aa7f-24231327e668 fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:12:41.653286+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=murmuring-badlands-7467.herokuapp.com request_id=674ba380-0640-48e6-a33d-6e963ab07c2a fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:18:29.445295+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=murmuring-badlands-7467.herokuapp.com request_id=1de9d4b2-6229-4c9e-91d5-b48a06d3a047 fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:18:29.724732+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=murmuring-badlands-7467.herokuapp.com request_id=bd85a952-7219-4492-90fd-f657a2557304 fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:23:06.691592+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=murmuring-badlands-7467.herokuapp.com request_id=f2a330a8-e3dd-43e8-970a-01121b24026f fwd="70.184.198.84" dyno= connect= service= status=503 bytes=
2015-07-17T16:23:07.003544+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=murmuring-badlands-7467.herokuapp.com request_id=58e951c6-a662-4ea1-a5a8-66e1308fb02f fwd="70.184.198.84" dyno= connect= service= status=503 bytes=

**Comment by david-at-ocs** [comment]
There were more logs.  But these are the ones that looked more to me like errors.

**Comment by david-at-ocs** [comment]
That's everything from the log

**Comment by sumeetjain** [comment]
The notable line is this:

`require': cannot load such file -- sqlite3`

It should strike you as odd that Heroku is trying to require SQLite, even though you specified that SQLite is only for development mode. Or did you...? ;)
